SELECT YEAR(EV.DATA) AS ANOEVENTO,
       COUNT(*) AS QTDELANCAMENTO,
	   MAX(ALTITUDE_MAXIMA) AS MAIORALTITUDE,
	   MIN(VELOCIDADE_MAXIMA) AS MENORVELOCIDADE,
	   AVG(DURACAO_VOO) AS MEDIADURACAOVOO
  FROM SC_EVENTO EV
	   INNER JOIN SC_FACULDADE FC ON EV.ID_FACULDADE = FC.ID_FACULDADE
	   INNER JOIN SC_TURMA T ON T.ID_FACULDADE = FC.ID_FACULDADE
       INNER JOIN SC_EQUIPE E ON E.ID_TURMA = T.ID_TURMA
       INNER JOIN SC_FOGUETE F ON E.ID_FOGUETE = F.ID_FOGUETE
	   INNER JOIN SC_LANCAMENTO L ON L.ID_FOGUETE = F.ID_FOGUETE
GROUP BY YEAR(EV.DATA)