CREATE TABLE SC_Aluno
  (
    MATRICULA NUMBER NOT NULL ,
    NOME      VARCHAR2 NOT NULL ,
    ID_EQUIPE NUMBER NOT NULL
  ) ;
ALTER TABLE SC_Aluno ADD CONSTRAINT Aluno_PK PRIMARY KEY ( MATRICULA ) ;

CREATE TABLE SC_Endereco
  (
    ID_ENDERECO NUMBER NOT NULL ,
    LOGRADOURO  VARCHAR2 NOT NULL ,
    CEP         VARCHAR2 NOT NULL ,
    NUMERO      NUMBER NOT NULL ,
    ID_EVENTO   NUMBER NOT NULL
  ) ;
  
  ALTER TABLE SC_Endereco ADD CONSTRAINT Endereco_PK PRIMARY KEY ( ID_ENDERECO ) ;

CREATE TABLE SC_Equipe
  (
    ID_EQUIPE  NUMBER NOT NULL ,
    NOME       VARCHAR2 NOT NULL ,
    ID_TURMA   NUMBER NOT NULL ,
    ID_FOGUETE NUMBER NOT NULL
  ) ;
 ALTER TABLE SC_Equipe ADD CONSTRAINT Equipe_PK PRIMARY KEY ( ID_EQUIPE ) ;

CREATE TABLE SC_Evento
  (
    ID_EVENTO    NUMBER NOT NULL ,
    DATA         DATE NOT NULL ,
    ID_FACULDADE NUMBER ,
    ID_ENDERECO  NUMBER NOT NULL ,
    ID_FISCAL    NUMBER NOT NULL
  ) ;
  ALTER TABLE SC_Evento ADD CONSTRAINT Evento_PK PRIMARY KEY ( ID_EVENTO ) ;

CREATE TABLE SC_Faculdade
  (
    ID_FACULDADE NUMBER NOT NULL ,
    NOME         VARCHAR2 NOT NULL
  ) ;
ALTER TABLE SC_Faculdade ADD CONSTRAINT FACULDADE_PK PRIMARY KEY ( ID_FACULDADE ) ;

CREATE TABLE Fiscal
  ( ID_FISCAL NUMBER NOT NULL , NOME VARCHAR2 NOT NULL
  ) ;
ALTER TABLE Fiscal ADD CONSTRAINT Fiscal_PK PRIMARY KEY ( ID_FISCAL ) ;

CREATE TABLE Foguete
  (
    ID_FOGUETE NUMBER NOT NULL ,
    NOME       VARCHAR2 NOT NULL ,
    PESO       NUMBER NOT NULL ,
    ALTRUA     NUMBER NOT NULL ,
    ID_EQUIPE  NUMBER NOT NULL
  ) ;
  ALTER TABLE Foguete ADD CONSTRAINT Foguete_PK PRIMARY KEY ( ID_FOGUETE ) ;

CREATE TABLE Lancamento
  (
    ID_LANCAMENTO        NUMBER NOT NULL ,
    ALTITUDE_MAXIMA      NUMBER NOT NULL ,
    VELOCIDADE_MAXIMA    NUMBER NOT NULL ,
    TEMPO_PROPULSAO      NUMBER NOT NULL ,
    PICO_ACELERACAO      NUMBER NOT NULL ,
    ACELERACAO_MEDIA     NUMBER NOT NULL ,
    TEMPO_APOGEU_DESCIDA NUMBER NOT NULL ,
    DISTANCIA_ALVO       NUMBER NOT NULL ,
    TEMPO_EJECAO         NUMBER NOT NULL ,
    ALTITUDE_EJECAO      NUMBER NOT NULL ,
    TAXA_DESCIDA         NUMBER NOT NULL ,
    DURACAO_VOO          NUMBER NOT NULL ,
    DATA                 DATE NOT NULL ,
    DISTANCIA_ATE_ALVO   NUMBER NOT NULL ,
    ANGULO               NUMBER NOT NULL ,
    VELOCIDADE_VENTO     NUMBER NOT NULL ,
    Foguete_ID_FOGUETE   NUMBER NOT NULL
  ) ;
ALTER TABLE Lancamento ADD CONSTRAINT Lancamento_PK PRIMARY KEY ( ID_LANCAMENTO ) ;

CREATE TABLE Turma
  (
    ID_TURMA     NUMBER NOT NULL ,
    NOME         VARCHAR2 NOT NULL ,
    NOME_CURSO   VARCHAR2 NOT NULL ,
    ID_FACULDADE NUMBER NOT NULL
  ) ;
ALTER TABLE Turma ADD CONSTRAINT Turma_PK PRIMARY KEY ( ID_TURMA ) ;


ALTER TABLE SC_Aluno ADD CONSTRAINT Aluno_Equipe_FK FOREIGN KEY ( ID_EQUIPE ) REFERENCES SC_Equipe ( ID_EQUIPE ) ;

ALTER TABLE SC_Endereco ADD CONSTRAINT Endereco_Evento_FK FOREIGN KEY ( ID_EVENTO ) REFERENCES SC_Evento ( ID_EVENTO ) ;

ALTER TABLE SC_Equipe ADD CONSTRAINT Equipe_Foguete_FK FOREIGN KEY ( ID_FOGUETE ) REFERENCES Foguete ( ID_FOGUETE ) ;

ALTER TABLE SC_Equipe ADD CONSTRAINT Equipe_Turma_FK FOREIGN KEY ( ID_TURMA ) REFERENCES Turma ( ID_TURMA ) ;

ALTER TABLE SC_Evento ADD CONSTRAINT Evento_Endereco_FK FOREIGN KEY ( ID_ENDERECO ) REFERENCES SC_Endereco ( ID_ENDERECO ) ;

ALTER TABLE SC_Evento ADD CONSTRAINT Evento_FACULDADE_FK FOREIGN KEY ( ID_FACULDADE ) REFERENCES SC_Faculdade ( ID_FACULDADE ) ;

ALTER TABLE SC_Evento ADD CONSTRAINT Evento_Fiscal_FK FOREIGN KEY ( ID_FISCAL ) REFERENCES Fiscal ( ID_FISCAL ) ;

ALTER TABLE Foguete ADD CONSTRAINT Foguete_Equipe_FK FOREIGN KEY ( ID_EQUIPE ) REFERENCES SC_Equipe ( ID_EQUIPE ) ;

ALTER TABLE Lancamento ADD CONSTRAINT Lancamento_Foguete_FK FOREIGN KEY ( Foguete_ID_FOGUETE ) REFERENCES Foguete ( ID_FOGUETE ) ;

ALTER TABLE Turma ADD CONSTRAINT Turma_FACULDADE_FK FOREIGN KEY ( ID_FACULDADE ) REFERENCES SC_Faculdade ( ID_FACULDADE ) ;