CREATE TABLE SC_Aluno
  (
    MATRICULA NUMBER(20) NOT NULL,
    NOME      VARCHAR2(50) NOT NULL,
    ID_EQUIPE NUMBER(20) NOT NULL
  );
ALTER TABLE SC_Aluno ADD CONSTRAINT Aluno_PK PRIMARY KEY ( MATRICULA );

CREATE TABLE SC_Endereco
  (
    ID_ENDERECO NUMBER(20) NOT NULL,
    LOGRADOURO  VARCHAR2(50) NOT NULL,
    CEP         VARCHAR2(50) NOT NULL,
    NUMERO      NUMBER(20) NOT NULL,
    ID_EVENTO   NUMBER(20) NOT NULL
  );
  
  ALTER TABLE SC_Endereco ADD CONSTRAINT Endereco_PK PRIMARY KEY ( ID_ENDERECO );

CREATE TABLE SC_Equipe
  (
    ID_EQUIPE  NUMBER(20) NOT NULL,
    NOME       VARCHAR2(50) NOT NULL,
    ID_TURMA   NUMBER(20) NOT NULL,
    ID_FOGUETE NUMBER(20) NOT NULL
  );
 ALTER TABLE SC_Equipe ADD CONSTRAINT Equipe_PK PRIMARY KEY ( ID_EQUIPE );

CREATE TABLE SC_Evento
  (
    ID_EVENTO    NUMBER(20) NOT NULL,
    DATA         DATE NOT NULL,
    ID_FACULDADE NUMBER(20),
    ID_ENDERECO  NUMBER(20) NOT NULL,
    ID_FISCAL    NUMBER(20) NOT NULL
  );
  ALTER TABLE SC_Evento ADD CONSTRAINT Evento_PK PRIMARY KEY ( ID_EVENTO );

CREATE TABLE SC_Faculdade
  (
    ID_FACULDADE NUMBER(20) NOT NULL,
    NOME         VARCHAR2(50) NOT NULL
  );
ALTER TABLE SC_Faculdade ADD CONSTRAINT FACULDADE_PK PRIMARY KEY ( ID_FACULDADE ) ;

CREATE TABLE SC_Fiscal
  ( ID_FISCAL NUMBER(20) NOT NULL, NOME VARCHAR2(50) NOT NULL
  );
ALTER TABLE SC_Fiscal ADD CONSTRAINT Fiscal_PK PRIMARY KEY ( ID_FISCAL );

CREATE TABLE SC_Foguete
  (
    ID_FOGUETE NUMBER(20) NOT NULL,
    NOME       VARCHAR2(50) NOT NULL,
    PESO       NUMBER(20) NOT NULL,
    ALTRUA     NUMBER(20) NOT NULL,
    ID_EQUIPE  NUMBER(20) NOT NULL
  );
  ALTER TABLE SC_Foguete ADD CONSTRAINT Foguete_PK PRIMARY KEY ( ID_FOGUETE );

CREATE TABLE SC_Lancamento
  (
    ID_LANCAMENTO        NUMBER(20) NOT NULL,
    ALTITUDE_MAXIMA      NUMBER(20) NOT NULL,
    VELOCIDADE_MAXIMA    NUMBER(20) NOT NULL,
    TEMPO_PROPULSAO      NUMBER(20) NOT NULL,
    PICO_ACELERACAO      NUMBER(20) NOT NULL,
    ACELERACAO_MEDIA     NUMBER(20) NOT NULL,
    TEMPO_APOGEU_DESCIDA NUMBER(20) NOT NULL,
    DISTANCIA_ALVO       NUMBER(20) NOT NULL,
    TEMPO_EJECAO         NUMBER(20) NOT NULL,
    ALTITUDE_EJECAO      NUMBER(20) NOT NULL,
    TAXA_DESCIDA         NUMBER(20) NOT NULL,
    DURACAO_VOO          NUMBER(20) NOT NULL,
    DATA                 DATE NOT NULL,
    DISTANCIA_ATE_ALVO   NUMBER(20) NOT NULL,
    ANGULO               NUMBER(20) NOT NULL,
    VELOCIDADE_VENTO     NUMBER(20) NOT NULL,
    Foguete_ID_FOGUETE   NUMBER(20) NOT NULL
  );
ALTER TABLE SC_Lancamento ADD CONSTRAINT Lancamento_PK1 PRIMARY KEY ( ID_LANCAMENTO );

CREATE TABLE SC_Turma
  (
    ID_TURMA     NUMBER(20) NOT NULL,
    NOME         VARCHAR2(50) NOT NULL,
    NOME_CURSO   VARCHAR2(50) NOT NULL,
    ID_FACULDADE NUMBER(20) NOT NULL
  );
ALTER TABLE SC_Turma ADD CONSTRAINT Turma_PK PRIMARY KEY ( ID_TURMA );


ALTER TABLE SC_Aluno ADD CONSTRAINT Aluno_Equipe_FK FOREIGN KEY ( ID_EQUIPE ) REFERENCES SC_Equipe ( ID_EQUIPE );

ALTER TABLE SC_Endereco ADD CONSTRAINT Endereco_Evento_FK FOREIGN KEY ( ID_EVENTO ) REFERENCES SC_Evento ( ID_EVENTO );

ALTER TABLE SC_Equipe ADD CONSTRAINT Equipe_Foguete_FK FOREIGN KEY ( ID_FOGUETE ) REFERENCES SC_Foguete ( ID_FOGUETE );

ALTER TABLE SC_Equipe ADD CONSTRAINT Equipe_Turma_FK FOREIGN KEY ( ID_TURMA ) REFERENCES SC_Turma ( ID_TURMA );

ALTER TABLE SC_Evento ADD CONSTRAINT Evento_Endereco_FK FOREIGN KEY ( ID_ENDERECO ) REFERENCES SC_Endereco ( ID_ENDERECO );

ALTER TABLE SC_Evento ADD CONSTRAINT Evento_FACULDADE_FK FOREIGN KEY ( ID_FACULDADE ) REFERENCES SC_Faculdade ( ID_FACULDADE );

ALTER TABLE SC_Evento ADD CONSTRAINT Evento_Fiscal_FK FOREIGN KEY ( ID_FISCAL ) REFERENCES SC_Fiscal ( ID_FISCAL );

ALTER TABLE SC_Foguete ADD CONSTRAINT Foguete_Equipe_FK FOREIGN KEY ( ID_EQUIPE ) REFERENCES SC_Equipe ( ID_EQUIPE );

ALTER TABLE SC_Lancamento ADD CONSTRAINT Lancamento_Foguete_FK FOREIGN KEY ( Foguete_ID_FOGUETE ) REFERENCES SC_Foguete ( ID_FOGUETE );

ALTER TABLE SC_Turma ADD CONSTRAINT Turma_FACULDADE_FK FOREIGN KEY ( ID_FACULDADE ) REFERENCES SC_Faculdade ( ID_FACULDADE );