ALTER TABLE SC_Aluno DROP CONSTRAINT Aluno_Equipe_FK;

ALTER TABLE SC_Endereco DROP CONSTRAINT Endereco_Evento_FK;

ALTER TABLE SC_Equipe DROP CONSTRAINT Equipe_Foguete_FK;

ALTER TABLE SC_Equipe DROP CONSTRAINT Equipe_Turma_FK;

ALTER TABLE SC_Evento DROP CONSTRAINT Evento_Endereco_FK;

ALTER TABLE SC_Evento DROP CONSTRAINT Evento_FACULDADE_FK;

ALTER TABLE SC_Evento DROP CONSTRAINT Evento_Fiscal_FK;

ALTER TABLE SC_Foguete DROP CONSTRAINT Foguete_Equipe_FK;

ALTER TABLE SC_Lancamento DROP CONSTRAINT Lancamento_Foguete_FK;

ALTER TABLE SC_Turma DROP CONSTRAINT Turma_FACULDADE_FK;

DROP TABLE SC_Aluno;

DROP TABLE SC_Endereco;

DROP TABLE SC_Equipe;

DROP TABLE SC_Evento:

DROP TABLE SC_Faculdade;

DROP TABLE SC_Fiscal;

DROP TABLE SC_Foguete;

DROP TABLE SC_Lancamento; 

DROP TABLE SC_Turma;

DROP TABLE SC_Lancamento; 