USE space_cup

BEGIN TRANSACTION

	DECLARE @ID_FOGUETE INT;
	DECLARE @ID_EQUIPE INT;

	SET @ID_EQUIPE = 1;

	DELETE FROM SC_Aluno WHERE ID_EQUIPE = @ID_EQUIPE

	SELECT @ID_FOGUETE = ID_FOGUETE FROM SC_Equipe WHERE ID_EQUIPE = @ID_EQUIPE

	DELETE FROM SC_Lancamento WHERE ID_FOGUETE = @ID_FOGUETE

	DELETE FROM SC_Equipe WHERE ID_EQUIPE = @ID_EQUIPE

	DELETE FROM SC_Foguete WHERE ID_FOGUETE = @ID_FOGUETE

COMMIT
