DECLARE @ANO INT
DECLARE @IDEQUIPE INT

SET @ANO = 2017
SET @IDEQUIPE = 1

SELECT E.NOME AS NOMEEQUIPE,
       L.*
  FROM SC_EVENTO EV
	   INNER JOIN SC_FACULDADE FC ON EV.ID_FACULDADE = FC.ID_FACULDADE
	   INNER JOIN SC_TURMA T ON T.ID_FACULDADE = FC.ID_FACULDADE
       INNER JOIN SC_EQUIPE E ON E.ID_TURMA = T.ID_TURMA
       INNER JOIN SC_FOGUETE F ON E.ID_FOGUETE = F.ID_FOGUETE
	   INNER JOIN SC_LANCAMENTO L ON L.ID_FOGUETE = F.ID_FOGUETE
 WHERE YEAR(EV.DATA) = @ANO AND E.ID_EQUIPE = @IDEQUIPE